name: pymmcore-plus-sandbox
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pip
  # TODO - released version of pymmcore-widgets not new enough - install from GitHub
  - pip:
    - "-e ."
variables:
  MICROMANAGER_PATH: /usr/local/bin/micromanager
